export const defaultTheme = {
  /* colorBlackForText: "#333333",
  colorWhite: "#ffffff",
  colorGray: "#f6f6f6",
  colorForLightBackground: "#D8ECFE",
  colorForDarkBackground: "#ffeead",
  colorForNewIcon: "#ffb334",
  colorForSoftIcon: "#7fc92e",
  colorForButton: "#FC9B27",
  colorForButtonHover: "#FC7427",
  colorForButtonActive: "#FC7427",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  footerHeight: "80px",
  pageWidth: "1280px" */
  fontColorBlack: "#333333",
  colorWhite: "#ffffff",
  backgroundColorGray: "#f7f7f7",
  backgroundColorBlue: "#d8ecfe",
  panelBackgroundColor: "#88aa4d",
  panelBackgroundColorDanger: "#f75531",
  buttonColor: "#fc9b27",
  buttonColorHoverActive: "#fc7427",
  pagePadding: "90px",
  indent: "20px",
  fontFamily: '"Inter", "Arial", sans-serif',
  fontSizeDefault: "18px",
  lineHeightDefault: 1.5,
  pageWidth: "1280px",
  headerHeight: "80px",
  footerHeight: "80px"
};
